apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: happiness-rating
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 2
    replication: 2  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
  acl:
    - team: teamsykmelding
      application: happiness-rating
      access: readwrite
    - team: teamsykmelding
      application: sykmeldinger
      access: write
