apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: happiness-dashboard
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: happiness-ratings
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://happiness-dashboard.intern.nav.no/'
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
